name: Pull Request Review.

on:
  pull_request_target:
    types:
      - review_requested

jobs:
  pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checking
        run: |
          echo PR review submitting.
    
