name: Pull Request Review.

on:
  pull_request_target:
    types:
      - review_requested
      
  workflow_call:

jobs:
  pr_review:
    runs-on: self-hosted
    steps:
      - name: Checking
        run: |
          echo PR review submitting.
    
